import type { CatalogAugment } from './catalog'

// 已登记固定 MIT ModRunes 与 ModScalability 的施法武器魂核分支。
export const CASTER_SOUL_CORES: readonly CatalogAugment[] = [
  {
    id: 'pob2:augment:["Opiloti\'s Soul Core of Assault","wand"]',
    name: "Opiloti's Soul Core of Assault",
    category: 'wand',
    type: 'SoulCore',
    localMod: false,
    lines: ['50% chance when you gain a Frenzy Charge to gain an additional Frenzy Charge'],
    statOrder: [5517],
    tradeHashes: {
      '2916861134': [
        '50% chance when you gain a Frenzy Charge to gain an additional Frenzy Charge',
      ],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
  },
  {
    id: 'pob2:augment:["Opiloti\'s Soul Core of Assault","staff"]',
    name: "Opiloti's Soul Core of Assault",
    category: 'staff',
    type: 'SoulCore',
    localMod: false,
    lines: ['50% chance when you gain a Frenzy Charge to gain an additional Frenzy Charge'],
    statOrder: [5517],
    tradeHashes: {
      '2916861134': [
        '50% chance when you gain a Frenzy Charge to gain an additional Frenzy Charge',
      ],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
  },
  {
    id: 'pob2:augment:["Guatelitzi\'s Soul Core of Endurance","wand"]',
    name: "Guatelitzi's Soul Core of Endurance",
    category: 'wand',
    type: 'SoulCore',
    localMod: false,
    lines: ['50% chance when you gain an Endurance Charge to gain an additional Endurance Charge'],
    statOrder: [5516],
    tradeHashes: {
      '1228682002': [
        '50% chance when you gain an Endurance Charge to gain an additional Endurance Charge',
      ],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
  },
  {
    id: 'pob2:augment:["Guatelitzi\'s Soul Core of Endurance","staff"]',
    name: "Guatelitzi's Soul Core of Endurance",
    category: 'staff',
    type: 'SoulCore',
    localMod: false,
    lines: ['50% chance when you gain an Endurance Charge to gain an additional Endurance Charge'],
    statOrder: [5516],
    tradeHashes: {
      '1228682002': [
        '50% chance when you gain an Endurance Charge to gain an additional Endurance Charge',
      ],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
  },
  {
    id: 'pob2:augment:["Xopec\'s Soul Core of Power","wand"]',
    name: "Xopec's Soul Core of Power",
    category: 'wand',
    type: 'SoulCore',
    localMod: false,
    lines: ['50% chance when you gain a Power Charge to gain an additional Power Charge'],
    statOrder: [5518],
    tradeHashes: {
      '3537994888': ['50% chance when you gain a Power Charge to gain an additional Power Charge'],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
  },
  {
    id: 'pob2:augment:["Xopec\'s Soul Core of Power","staff"]',
    name: "Xopec's Soul Core of Power",
    category: 'staff',
    type: 'SoulCore',
    localMod: false,
    lines: ['50% chance when you gain a Power Charge to gain an additional Power Charge'],
    statOrder: [5518],
    tradeHashes: {
      '3537994888': ['50% chance when you gain a Power Charge to gain an additional Power Charge'],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
  },
  {
    id: 'pob2:augment:["Xipocado\'s Soul Core of Dominion","wand"]',
    name: "Xipocado's Soul Core of Dominion",
    category: 'wand',
    type: 'SoulCore',
    localMod: false,
    lines: ['Minions deal 40% increased Damage with Command Skills'],
    statOrder: [9027],
    tradeHashes: {
      '3742865955': ['Minions deal 40% increased Damage with Command Skills'],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
  },
  {
    id: 'pob2:augment:["Xipocado\'s Soul Core of Dominion","staff"]',
    name: "Xipocado's Soul Core of Dominion",
    category: 'staff',
    type: 'SoulCore',
    localMod: false,
    lines: ['Minions deal 40% increased Damage with Command Skills'],
    statOrder: [9027],
    tradeHashes: {
      '3742865955': ['Minions deal 40% increased Damage with Command Skills'],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
  },
  {
    id: 'pob2:augment:["Soul Core of Vizoma","wand"]',
    name: 'Soul Core of Vizoma',
    category: 'wand',
    type: 'SoulCore',
    localMod: false,
    lines: ['30% increased Critical Hit Chance for Spells'],
    statOrder: [978],
    tradeHashes: {
      '737908626': ['30% increased Critical Hit Chance for Spells'],
    },
    levelReq: 0,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
  },
  {
    id: 'pob2:augment:["Soul Core of Vizoma","staff"]',
    name: 'Soul Core of Vizoma',
    category: 'staff',
    type: 'SoulCore',
    localMod: false,
    lines: ['30% increased Critical Hit Chance for Spells'],
    statOrder: [978],
    tradeHashes: {
      '737908626': ['30% increased Critical Hit Chance for Spells'],
    },
    levelReq: 0,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
  },
]
export const CASTER_SOUL_SCALABILITY = {
  '50% chance when you gain a Frenzy Charge to gain an additional Frenzy Charge': [
    {
      scalable: true,
      formats: [],
    },
  ],
  '50% chance when you gain an Endurance Charge to gain an additional Endurance Charge': [
    {
      scalable: true,
      formats: [],
    },
  ],
  '50% chance when you gain a Power Charge to gain an additional Power Charge': [
    {
      scalable: true,
      formats: [],
    },
  ],
  'Minions deal 40% increased Damage with Command Skills': [
    {
      scalable: true,
      formats: [],
    },
  ],
  '30% increased Critical Hit Chance for Spells': [
    {
      scalable: true,
      formats: [],
    },
  ],
}
