import type { CatalogAugment, CatalogBase, CatalogStatScalar } from './catalog'

// 固定 MIT PoB2 目录快照；只供身份和逐占位来源核对，不扩展 canSocketIn* 权限。
export const SCEPTRE_RECORDS: readonly CatalogAugment[] = [
  {
    id: 'pob2:augment:["Xipocado\'s Soul Core of Dominion","sceptre"]',
    name: "Xipocado's Soul Core of Dominion",
    category: 'sceptre',
    type: 'SoulCore',
    localMod: false,
    lines: ['Minions deal 40% increased Damage with Command Skills'],
    statOrder: [9027],
    tradeHashes: {
      '3742865955': ['Minions deal 40% increased Damage with Command Skills'],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
  },
  {
    id: 'pob2:augment:["Warding Rune of Salvaging","sceptre"]',
    name: 'Warding Rune of Salvaging',
    category: 'sceptre',
    type: 'Rune',
    localMod: false,
    lines: ['Recover 3% of maximum Runic Ward when one of your Reviving Minions is Killed'],
    statOrder: [9709],
    tradeHashes: {
      '3515226849': [
        'Recover 3% of maximum Runic Ward when one of your Reviving Minions is Killed',
      ],
    },
    levelReq: 30,
    limit: 1,
    canSocketInChakraSlots: true,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['Recover 3% of maximum Life when one of your Minions is Revived'],
      statOrder: [10605],
    },
  },
  {
    id: 'pob2:augment:["Warding Rune of Bodyguards","sceptre"]',
    name: 'Warding Rune of Bodyguards',
    category: 'sceptre',
    type: 'Rune',
    localMod: false,
    lines: ['Minions in your Presence have Onslaught while you are on Low Runic Ward'],
    statOrder: [9109],
    tradeHashes: {
      '540694930': ['Minions in your Presence have Onslaught while you are on Low Runic Ward'],
    },
    levelReq: 45,
    limit: 1,
    canSocketInChakraSlots: true,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: [
        'Damage of Enemies Hitting you is Unlucky if',
        'your Runic Ward has been damaged Recently',
      ],
      statOrder: [6038, 6038.1],
    },
  },
  {
    id: 'pob2:augment:["Ancient Rune of the Horde","sceptre"]',
    name: 'Ancient Rune of the Horde',
    category: 'sceptre',
    type: 'Rune',
    localMod: false,
    lines: ['Minions have 8% increased Attack and Cast Speed'],
    statOrder: [9003],
    tradeHashes: {
      '3091578504': ['Minions have 8% increased Attack and Cast Speed'],
    },
    levelReq: 30,
    limit: 1,
    canSocketInChakraSlots: true,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['Minions have 10% increased Movement Speed'],
      statOrder: [1528],
    },
  },
  {
    id: 'pob2:augment:["Rune of the Hunt","sceptre"]',
    name: 'Rune of the Hunt',
    category: 'sceptre',
    type: 'Rune',
    localMod: false,
    lines: ['Companions deal 30% increased Damage'],
    statOrder: [5719],
    tradeHashes: {
      '234296660': ['Companions deal 30% increased Damage'],
    },
    levelReq: 15,
    limit: 1,
    canSocketInChakraSlots: true,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['8% increased Mana Recovery rate while your Companion is in your Presence'],
      statOrder: [7997],
    },
  },
  {
    id: 'pob2:augment:["Idol of Sirrius","sceptre"]',
    name: 'Idol of Sirrius',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['Allies in your Presence have 8% increased Movement Speed'],
    statOrder: [4287],
    tradeHashes: {
      '632743438': ['Allies in your Presence have 8% increased Movement Speed'],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['4% increased Movement Speed'],
      statOrder: [836],
    },
  },
  {
    id: 'pob2:augment:["Idol of Thruldana","sceptre"]',
    name: 'Idol of Thruldana',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['Allies in your Presence deal 13 to 27 added Attack Chaos Damage'],
    statOrder: [911],
    tradeHashes: {
      '262946222': ['Allies in your Presence deal 13 to 27 added Attack Chaos Damage'],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['15% increased Withered Magnitude'],
      statOrder: [10565],
    },
  },
  {
    id: 'pob2:augment:["Idol of Grold","sceptre"]',
    name: 'Idol of Grold',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['15% increased Damage per each different Companion in your Presence'],
    statOrder: [5949],
    tradeHashes: {
      '3151560620': ['15% increased Damage per each different Companion in your Presence'],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['15% increased Reservation Efficiency of Companion Skills'],
      statOrder: [9766],
    },
  },
  {
    id: 'pob2:augment:["Idol of Eeshta","sceptre"]',
    name: 'Idol of Eeshta',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['15% increased Mana Recovery rate while your Companion is in your Presence'],
    statOrder: [7997],
    tradeHashes: {
      '1779262102': ['15% increased Mana Recovery rate while your Companion is in your Presence'],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['8% increased Life Recovery Rate while your Companion is in your Presence'],
      statOrder: [7486],
    },
  },
  {
    id: 'pob2:augment:["Idol of Egrin","sceptre"]',
    name: 'Idol of Egrin',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['20% increased Curse Duration'],
    statOrder: [1540],
    tradeHashes: {
      '3824372849': ['20% increased Curse Duration'],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['Curse zones erupt after 20% reduced delay'],
      statOrder: [4677],
    },
  },
  {
    id: 'pob2:augment:["Idol of Maxarius","sceptre"]',
    name: 'Idol of Maxarius',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['Flasks gain 0.2 charges per Second'],
    statOrder: [6886],
    tradeHashes: {
      '731781020': ['Flasks gain 0.2 charges per Second'],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['20% increased Life and Mana Recovery from Flasks'],
      statOrder: [6641],
    },
  },
  {
    id: 'pob2:augment:["Idol of Ralakesh","sceptre"]',
    name: 'Idol of Ralakesh',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: [
      '40% increased Armour, Evasion and Energy Shield while your Companion is in your Presence',
    ],
    statOrder: [6902],
    tradeHashes: {
      '2829985691': [
        '40% increased Armour, Evasion and Energy Shield while your Companion is in your Presence',
      ],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['Companions have 25% increased maximum Life'],
      statOrder: [5723],
    },
  },
  {
    id: 'pob2:augment:["Snake Idol","sceptre"]',
    name: 'Snake Idol',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['Allies in your Presence have 10% increased Attack Speed'],
    statOrder: [918],
    tradeHashes: {
      '1998951374': ['Allies in your Presence have 10% increased Attack Speed'],
    },
    levelReq: 0,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['10% increased Skill Speed while Shapeshifted'],
      statOrder: [9918],
    },
  },
  {
    id: 'pob2:augment:["Primate Idol","sceptre"]',
    name: 'Primate Idol',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['Allies in your Presence deal 40% increased Damage'],
    statOrder: [906],
    tradeHashes: {
      '1798257884': ['Allies in your Presence deal 40% increased Damage'],
    },
    levelReq: 0,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['40% increased Damage while Shapeshifted'],
      statOrder: [5958],
    },
  },
  {
    id: 'pob2:augment:["Owl Idol","sceptre"]',
    name: 'Owl Idol',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['Allies in your Presence have 10% increased Cast Speed'],
    statOrder: [919],
    tradeHashes: {
      '289128254': ['Allies in your Presence have 10% increased Cast Speed'],
    },
    levelReq: 0,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['10% increased Skill Speed while Shapeshifted'],
      statOrder: [9918],
    },
  },
  {
    id: 'pob2:augment:["Cat Idol","sceptre"]',
    name: 'Cat Idol',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['Allies in your Presence have 14% increased Critical Hit Chance'],
    statOrder: [916],
    tradeHashes: {
      '1250712710': ['Allies in your Presence have 14% increased Critical Hit Chance'],
    },
    levelReq: 0,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['25% increased Critical Hit Chance while Shapeshifted'],
      statOrder: [5832],
    },
  },
  {
    id: 'pob2:augment:["Wolf Idol","sceptre"]',
    name: 'Wolf Idol',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['Allies in your Presence have 20% increased Critical Damage Bonus'],
    statOrder: [917],
    tradeHashes: {
      '3057012405': ['Allies in your Presence have 20% increased Critical Damage Bonus'],
    },
    levelReq: 0,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['25% increased Critical Hit Chance while Shapeshifted'],
      statOrder: [5832],
    },
  },
  {
    id: 'pob2:augment:["Stag Idol","sceptre"]',
    name: 'Stag Idol',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['Allies in your Presence deal 1 to 40 added Attack Lightning Damage'],
    statOrder: [910],
    tradeHashes: {
      '2854751904': ['Allies in your Presence deal 1 to 40 added Attack Lightning Damage'],
    },
    levelReq: 0,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['40% increased Attack Damage while Shapeshifted'],
      statOrder: [4519],
    },
  },
  {
    id: 'pob2:augment:["Boar Idol","sceptre"]',
    name: 'Boar Idol',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['Allies in your Presence Regenerate 0.5% of your Maximum Life per second'],
    statOrder: [923],
    tradeHashes: {
      '1911097163': ['Allies in your Presence Regenerate 0.5% of your Maximum Life per second'],
    },
    levelReq: 0,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['25% increased Life Regeneration rate while Shapeshifted'],
      statOrder: [7505],
    },
  },
  {
    id: 'pob2:augment:["Bear Idol","sceptre"]',
    name: 'Bear Idol',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['Allies in your Presence deal 12 to 18 added Attack Physical Damage'],
    statOrder: [907],
    tradeHashes: {
      '1574590649': ['Allies in your Presence deal 12 to 18 added Attack Physical Damage'],
    },
    levelReq: 0,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['40% increased Attack Damage while Shapeshifted'],
      statOrder: [4519],
    },
  },
  {
    id: 'pob2:augment:["Ox Idol","sceptre"]',
    name: 'Ox Idol',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['Allies in your Presence have +12% to all Elemental Resistances'],
    statOrder: [920],
    tradeHashes: {
      '3850614073': ['Allies in your Presence have +12% to all Elemental Resistances'],
    },
    levelReq: 0,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['+20% of Armour also applies to Elemental Damage while Shapeshifted'],
      statOrder: [10573],
    },
  },
  {
    id: 'pob2:augment:["Rabbit Idol","sceptre"]',
    name: 'Rabbit Idol',
    category: 'sceptre',
    type: 'Idol',
    localMod: true,
    lines: ['15% increased Spirit'],
    statOrder: [857],
    tradeHashes: {
      '3984865854': ['15% increased Spirit'],
    },
    levelReq: 0,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['Minions have 30% increased Cooldown Recovery Rate for Command Skills'],
      statOrder: [9024],
    },
  },
  {
    id: 'pob2:augment:["Fox Idol","sceptre"]',
    name: 'Fox Idol',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['50% increased Presence Area of Effect'],
    statOrder: [1069],
    tradeHashes: {
      '101878827': ['50% increased Presence Area of Effect'],
    },
    levelReq: 0,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['Minions have 30% increased Area of Effect'],
      statOrder: [2759],
    },
  },
  {
    id: 'pob2:augment:["Idol of Greust","sceptre"]',
    name: 'Idol of Greust',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['Companions deal 10% more Damage for each different type of dead Companion you have'],
    statOrder: [5716],
    tradeHashes: {
      '2882351629': [
        'Companions deal 10% more Damage for each different type of dead Companion you have',
      ],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['Recover 3% of maximum Life when one of your Minions is Revived'],
      statOrder: [10605],
    },
  },
  {
    id: 'pob2:augment:["Idol of Yeena","sceptre"]',
    name: 'Idol of Yeena',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: [
      'Plants have a 25% chance to immediately Overgrow when they enter your Presence for the first time',
    ],
    statOrder: [5362],
    tradeHashes: {
      '2681952497': [
        'Plants have a 25% chance to immediately Overgrow when they enter your Presence for the first time',
      ],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['30% increased Skill Effect Duration with Plant Skills'],
      statOrder: [9488],
    },
  },
  {
    id: 'pob2:augment:["Idol of Eramir","sceptre"]',
    name: 'Idol of Eramir',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['Allies in your Presence share Charges with you'],
    statOrder: [4290],
    tradeHashes: {
      '3329501096': ['Allies in your Presence share Charges with you'],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['25% increased Endurance, Frenzy and Power Charge Duration'],
      statOrder: [2761],
    },
  },
  {
    id: 'pob2:augment:["Idol of Oak","sceptre"]',
    name: 'Idol of Oak',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: [
      'If you would gain an Endurance Charge, Allies in your Presence gain that Charge instead',
    ],
    statOrder: [2010],
    tradeHashes: {
      '1881314095': [
        'If you would gain an Endurance Charge, Allies in your Presence gain that Charge instead',
      ],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ["40% increased Armour if you've consumed an Endurance Charge Recently"],
      statOrder: [4387],
    },
  },
  {
    id: 'pob2:augment:["Idol of Alira","sceptre"]',
    name: 'Idol of Alira',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['If you would gain a Power Charge, Allies in your Presence gain that Charge instead'],
    statOrder: [2012],
    tradeHashes: {
      '4226127445': [
        'If you would gain a Power Charge, Allies in your Presence gain that Charge instead',
      ],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ["40% increased maximum Energy Shield if you've consumed a Power Charge Recently"],
      statOrder: [6414],
    },
  },
  {
    id: 'pob2:augment:["Idol of Kraityn","sceptre"]',
    name: 'Idol of Kraityn',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['If you would gain a Frenzy Charge, Allies in your Presence gain that Charge instead'],
    statOrder: [2011],
    tradeHashes: {
      '2211478554': [
        'If you would gain a Frenzy Charge, Allies in your Presence gain that Charge instead',
      ],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ["40% increased Evasion Rating if you've consumed a Frenzy Charge Recently"],
      statOrder: [6485],
    },
  },
  {
    id: 'pob2:augment:["Idol of Silk","sceptre"]',
    name: 'Idol of Silk',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['Companions in your Presence gain 1 Rage on hit'],
    statOrder: [5736],
    tradeHashes: {
      '2652394701': ['Companions in your Presence gain 1 Rage on hit'],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['Companions have 30% increased Area of Effect'],
      statOrder: [5712],
    },
  },
  {
    id: 'pob2:augment:["Idol of the Sycophant","sceptre"]',
    name: 'Idol of the Sycophant',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: [
      'Companions in your Presence have -20% to all Elemental Resistances',
      'Companions in your Presence Gain 20% of Damage as Extra Damage of a random Element',
    ],
    statOrder: [5734, 5739],
    tradeHashes: {
      '1539508682': ['Companions in your Presence have -20% to all Elemental Resistances'],
      '4200448078': [
        'Companions in your Presence Gain 20% of Damage as Extra Damage of a random Element',
      ],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: [
        'Allies in your Presence Gain 20% of Damage as Extra Chaos Damage',
        'Companions in your Presence have -20% to Chaos Resistance',
      ],
      statOrder: [4288, 5733],
    },
  },
  {
    id: 'pob2:augment:["Idol of the Martyr","sceptre"]',
    name: 'Idol of the Martyr',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['40% reduced Presence Area of Effect', 'Aura Skills have 25% increased Magnitudes'],
    statOrder: [1069, 2574],
    tradeHashes: {
      '101878827': ['40% reduced Presence Area of Effect'],
      '315791320': ['Aura Skills have 25% increased Magnitudes'],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: [
        'Allies in your Presence Regenerate 3% of your Maximum Life per second',
        '25% reduced Life Regeneration rate',
      ],
      statOrder: [923, 1036],
    },
  },
  {
    id: 'pob2:augment:["Idol of the Pharisee","sceptre"]',
    name: 'Idol of the Pharisee',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: [
      '30% reduced Mana Cost Efficiency of Command Skills',
      'Minions deal 60% increased Damage with Command Skills',
    ],
    statOrder: [4718, 9027],
    tradeHashes: {
      '553018427': ['30% reduced Mana Cost Efficiency of Command Skills'],
      '3742865955': ['Minions deal 60% increased Damage with Command Skills'],
    },
    levelReq: 50,
    limit: 1,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: [
        '25% reduced Reservation Efficiency of Minion Skills',
        'Temporary Minion Skills have +2 to Limit of Minions summoned',
      ],
      statOrder: [9769, 10254],
    },
  },
  {
    id: 'pob2:augment:["Panther Idol","sceptre"]',
    name: 'Panther Idol',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['Minions have +20% to Chaos Resistance'],
    statOrder: [2668],
    tradeHashes: {
      '3837707023': ['Minions have +20% to Chaos Resistance'],
    },
    levelReq: 50,
    limit: 1,
    canSocketInChakraSlots: true,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['Minions have 20% additional Physical Damage Reduction'],
      statOrder: [2022],
    },
  },
  {
    id: 'pob2:augment:["Hawk Idol","sceptre"]',
    name: 'Hawk Idol',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['Companions have 12% increased Attack Speed'],
    statOrder: [5713],
    tradeHashes: {
      '666077204': ['Companions have 12% increased Attack Speed'],
    },
    levelReq: 50,
    limit: 1,
    canSocketInChakraSlots: true,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['8% increased Attack Speed while your Companion is in your Presence'],
      statOrder: [4556],
    },
  },
  {
    id: 'pob2:augment:["Stoat Idol","sceptre"]',
    name: 'Stoat Idol',
    category: 'sceptre',
    type: 'Idol',
    localMod: false,
    lines: ['Companions have 25% increased maximum Life'],
    statOrder: [5723],
    tradeHashes: {
      '1805182458': ['Companions have 25% increased maximum Life'],
    },
    levelReq: 50,
    limit: 1,
    canSocketInChakraSlots: true,
    canSocketInUniqueItems: true,
    canSocketInJewellery: true,
    canSocketInCorruptedSanctified: true,
    bonded: {
      lines: ['25% increased Damage while your Companion is in your Presence'],
      statOrder: [5957],
    },
  },
]
export const SCEPTRE_BASES: readonly CatalogBase[] = [
  {
    id: 'Aromatic Sceptre',
    name: 'Aromatic Sceptre',
    type: 'Sceptre',
    tags: ['default', 'onehand', 'sceptre'],
    requirements: {
      level: 52,
      int: 92,
    },
    properties: {},
    implicit: 'Grants Skill: Level (1-20) Skeletal Warrior Minion',
    implicitTags: [],
    sourceQuality: 20,
    socketLimit: 3,
    hidden: false,
    runeforged: false,
    spirit: 100,
  },
  {
    id: 'Clasped Sceptre',
    name: 'Clasped Sceptre',
    type: 'Sceptre',
    tags: ['default', 'onehand', 'sceptre'],
    requirements: {
      level: 36,
      int: 65,
    },
    properties: {},
    implicit: 'Grants Skill: Level (1-20) Heart of Ice',
    implicitTags: [],
    sourceQuality: 20,
    socketLimit: 3,
    hidden: false,
    runeforged: false,
    spirit: 100,
  },
  {
    id: 'Devotional Sceptre',
    name: 'Devotional Sceptre',
    type: 'Sceptre',
    tags: ['default', 'onehand', 'sceptre'],
    requirements: {
      level: 45,
      str: 26,
      int: 63,
    },
    properties: {},
    implicit: 'Grants Skill: Level (1-20) Skeletal Warrior Minion',
    implicitTags: [],
    sourceQuality: 20,
    socketLimit: 3,
    hidden: false,
    runeforged: false,
    spirit: 100,
  },
  {
    id: 'Devouring Sceptre',
    name: 'Devouring Sceptre',
    type: 'Sceptre',
    tags: ['default', 'onehand', 'sceptre'],
    requirements: {
      level: 33,
      int: 60,
    },
    properties: {},
    implicit: 'Grants Skill: Level (1-20) Skeletal Warrior Minion',
    implicitTags: [],
    sourceQuality: 20,
    socketLimit: 3,
    hidden: false,
    runeforged: false,
    spirit: 100,
  },
  {
    id: 'Hallowed Sceptre',
    name: 'Hallowed Sceptre',
    type: 'Sceptre',
    tags: ['default', 'onehand', 'sceptre'],
    requirements: {
      level: 65,
      int: 114,
    },
    properties: {},
    implicit: 'Grants Skill: Level (1-20) Skeletal Warrior Minion',
    implicitTags: [],
    sourceQuality: 20,
    socketLimit: 3,
    hidden: false,
    runeforged: false,
    spirit: 100,
  },
  {
    id: 'Lupine Sceptre',
    name: 'Lupine Sceptre',
    type: 'Sceptre',
    tags: ['default', 'onehand', 'sceptre'],
    requirements: {
      level: 12,
      int: 24,
    },
    properties: {},
    implicit: 'Grants Skill: Level (1-20) Skeletal Warrior Minion',
    implicitTags: [],
    sourceQuality: 20,
    socketLimit: 3,
    hidden: false,
    runeforged: false,
    spirit: 100,
  },
  {
    id: 'Ochre Sceptre',
    name: 'Ochre Sceptre',
    type: 'Sceptre',
    tags: ['default', 'onehand', 'sceptre'],
    requirements: {
      level: 21,
      int: 40,
    },
    properties: {},
    implicit: 'Grants Skill: Level (1-20) Skeletal Warrior Minion',
    implicitTags: [],
    sourceQuality: 20,
    socketLimit: 3,
    hidden: false,
    runeforged: false,
    spirit: 100,
  },
  {
    id: 'Omen Sceptre',
    name: 'Omen Sceptre',
    type: 'Sceptre',
    tags: ['default', 'onehand', 'sceptre'],
    requirements: {
      level: 16,
      str: 12,
      int: 25,
    },
    properties: {},
    implicit: 'Grants Skill: Level (1-20) Malice',
    implicitTags: [],
    sourceQuality: 20,
    socketLimit: 3,
    hidden: false,
    runeforged: false,
    spirit: 100,
  },
  {
    id: 'Pious Sceptre',
    name: 'Pious Sceptre',
    type: 'Sceptre',
    tags: ['default', 'onehand', 'sceptre'],
    requirements: {
      level: 58,
      int: 102,
    },
    properties: {},
    implicit: 'Grants Skill: Level (1-20) Skeletal Warrior Minion',
    implicitTags: [],
    sourceQuality: 20,
    socketLimit: 3,
    hidden: false,
    runeforged: false,
    spirit: 100,
  },
  {
    id: 'Rattling Sceptre',
    name: 'Rattling Sceptre',
    type: 'Sceptre',
    tags: ['default', 'onehand', 'physical_implicit_skill', 'sceptre'],
    requirements: {},
    properties: {},
    implicit: 'Grants Skill: Level (1-20) Skeletal Warrior Minion',
    implicitTags: [],
    sourceQuality: 20,
    socketLimit: 3,
    hidden: false,
    runeforged: false,
    spirit: 100,
  },
  {
    id: 'pob2:base:v1:280d180dd8d9777ac5742699fe476812089a3c6079b2119af739d7011a86c312',
    name: 'Shrine Sceptre',
    type: 'Sceptre',
    tags: ['default', 'lightning_implicit_skill', 'onehand', 'sceptre'],
    requirements: {
      level: 26,
      str: 17,
      int: 38,
    },
    properties: {},
    implicit: 'Grants Skill: Level (1-20) Purity of Lightning',
    implicitTags: [],
    sourceQuality: 20,
    socketLimit: 3,
    hidden: false,
    runeforged: false,
    spirit: 100,
    variant: {
      visibility: 'mixed',
      declarations: [
        {
          sourcePath: 'src/Data/Bases/sceptre.lua',
          index: 7,
          hidden: false,
        },
        {
          sourcePath: 'src/Data/Bases/sceptre.lua',
          index: 17,
          hidden: true,
        },
      ],
    },
  },
  {
    id: 'pob2:base:v1:da96ba6e82bc4f728a6869a820a1a58e202b756ba028962e2880cc49b11d0ecb',
    name: 'Shrine Sceptre',
    type: 'Sceptre',
    tags: ['cold_implicit_skill', 'default', 'onehand', 'sceptre'],
    requirements: {
      level: 26,
      str: 17,
      int: 38,
    },
    properties: {},
    implicit: 'Grants Skill: Level (1-20) Purity of Ice',
    implicitTags: [],
    sourceQuality: 20,
    socketLimit: 3,
    hidden: false,
    runeforged: false,
    spirit: 100,
    variant: {
      visibility: 'mixed',
      declarations: [
        {
          sourcePath: 'src/Data/Bases/sceptre.lua',
          index: 6,
          hidden: false,
        },
        {
          sourcePath: 'src/Data/Bases/sceptre.lua',
          index: 16,
          hidden: true,
        },
      ],
    },
  },
  {
    id: 'pob2:base:v1:dcd71ddcdf6c8b9b814e7291ddad228282eb40106386f7178bd1fde3192459ca',
    name: 'Shrine Sceptre',
    type: 'Sceptre',
    tags: ['default', 'fire_implicit_skill', 'onehand', 'sceptre'],
    requirements: {
      level: 26,
      str: 17,
      int: 38,
    },
    properties: {},
    implicit: 'Grants Skill: Level (1-20) Purity of Fire',
    implicitTags: [],
    sourceQuality: 20,
    socketLimit: 3,
    hidden: false,
    runeforged: false,
    spirit: 100,
    variant: {
      visibility: 'mixed',
      declarations: [
        {
          sourcePath: 'src/Data/Bases/sceptre.lua',
          index: 5,
          hidden: false,
        },
        {
          sourcePath: 'src/Data/Bases/sceptre.lua',
          index: 15,
          hidden: true,
        },
      ],
    },
  },
  {
    id: 'Shrine Sceptre (Purity of Cold)',
    name: 'Shrine Sceptre (Purity of Cold)',
    type: 'Sceptre',
    tags: ['cold_implicit_skill', 'default', 'onehand', 'sceptre'],
    requirements: {
      level: 26,
      str: 17,
      int: 38,
    },
    properties: {},
    implicit: 'Grants Skill: Level (1-20) Purity of Ice',
    implicitTags: [],
    sourceQuality: 20,
    socketLimit: 3,
    hidden: false,
    runeforged: false,
    spirit: 100,
  },
  {
    id: 'Shrine Sceptre (Purity of Fire)',
    name: 'Shrine Sceptre (Purity of Fire)',
    type: 'Sceptre',
    tags: ['default', 'fire_implicit_skill', 'onehand', 'sceptre'],
    requirements: {
      level: 26,
      str: 17,
      int: 38,
    },
    properties: {},
    implicit: 'Grants Skill: Level (1-20) Purity of Fire',
    implicitTags: [],
    sourceQuality: 20,
    socketLimit: 3,
    hidden: false,
    runeforged: false,
    spirit: 100,
  },
  {
    id: 'Shrine Sceptre (Purity of Lighting)',
    name: 'Shrine Sceptre (Purity of Lighting)',
    type: 'Sceptre',
    tags: ['default', 'lightning_implicit_skill', 'onehand', 'sceptre'],
    requirements: {
      level: 26,
      str: 17,
      int: 38,
    },
    properties: {},
    implicit: 'Grants Skill: Level (1-20) Purity of Lightning',
    implicitTags: [],
    sourceQuality: 20,
    socketLimit: 3,
    hidden: false,
    runeforged: false,
    spirit: 100,
  },
  {
    id: 'Stoic Sceptre',
    name: 'Stoic Sceptre',
    type: 'Sceptre',
    tags: ['default', 'onehand', 'sceptre'],
    requirements: {
      level: 6,
      int: 12,
    },
    properties: {},
    implicit: 'Grants Skill: Level (1-20) Discipline',
    implicitTags: [],
    sourceQuality: 20,
    socketLimit: 3,
    hidden: false,
    runeforged: false,
    spirit: 100,
  },
  {
    id: 'Wrath Sceptre',
    name: 'Wrath Sceptre',
    type: 'Sceptre',
    tags: ['default', 'lightning_implicit_skill', 'onehand', 'sceptre'],
    requirements: {
      level: 49,
      int: 87,
    },
    properties: {},
    implicit: 'Grants Skill: Level (1-20) Fulmination',
    implicitTags: [],
    sourceQuality: 20,
    socketLimit: 3,
    hidden: false,
    runeforged: false,
    spirit: 100,
  },
]
export const SCEPTRE_SCALABILITY: Readonly<Record<string, readonly CatalogStatScalar[]>> = {
  'Minions deal 40% increased Damage with Command Skills': [
    {
      scalable: true,
      formats: [],
    },
  ],
  'Recover 3% of maximum Runic Ward when one of your Reviving Minions is Killed': [
    {
      scalable: true,
      formats: [],
    },
  ],
  'Minions in your Presence have Onslaught while you are on Low Runic Ward': [],
  'Minions have 8% increased Attack and Cast Speed': [
    {
      scalable: true,
      formats: [],
    },
  ],
  'Companions deal 30% increased Damage': [
    {
      scalable: true,
      formats: [],
    },
  ],
  'Allies in your Presence have 8% increased Movement Speed': [
    {
      scalable: true,
      formats: [],
    },
  ],
  'Allies in your Presence deal 13 to 27 added Attack Chaos Damage': [
    {
      scalable: true,
      formats: [],
    },
    {
      scalable: true,
      formats: [],
    },
  ],
  '15% increased Damage per each different Companion in your Presence': [
    {
      scalable: true,
      formats: [],
    },
  ],
  '15% increased Mana Recovery rate while your Companion is in your Presence': [
    {
      scalable: true,
      formats: [],
    },
  ],
  '20% increased Curse Duration': [
    {
      scalable: true,
      formats: [],
    },
  ],
  'Flasks gain 0.2 charges per Second': [
    {
      scalable: true,
      formats: ['per_minute_to_per_second_2dp_if_required'],
    },
  ],
  '40% increased Armour, Evasion and Energy Shield while your Companion is in your Presence': [
    {
      scalable: true,
      formats: [],
    },
  ],
  'Allies in your Presence have 10% increased Attack Speed': [
    {
      scalable: true,
      formats: [],
    },
  ],
  'Allies in your Presence deal 40% increased Damage': [
    {
      scalable: true,
      formats: [],
    },
  ],
  'Allies in your Presence have 10% increased Cast Speed': [
    {
      scalable: true,
      formats: [],
    },
  ],
  'Allies in your Presence have 14% increased Critical Hit Chance': [
    {
      scalable: true,
      formats: [],
    },
  ],
  'Allies in your Presence have 20% increased Critical Damage Bonus': [
    {
      scalable: true,
      formats: [],
    },
  ],
  'Allies in your Presence deal 1 to 40 added Attack Lightning Damage': [
    {
      scalable: true,
      formats: [],
    },
    {
      scalable: true,
      formats: [],
    },
  ],
  'Allies in your Presence Regenerate 0.5% of your Maximum Life per second': [
    {
      scalable: true,
      formats: ['per_minute_to_per_second'],
    },
  ],
  'Allies in your Presence deal 12 to 18 added Attack Physical Damage': [
    {
      scalable: true,
      formats: [],
    },
    {
      scalable: true,
      formats: [],
    },
  ],
  'Allies in your Presence have +12% to all Elemental Resistances': [
    {
      scalable: true,
      formats: [],
    },
  ],
  '15% increased Spirit': [
    {
      scalable: true,
      formats: [],
    },
  ],
  '50% increased Presence Area of Effect': [
    {
      scalable: true,
      formats: [],
    },
  ],
  'Companions deal 10% more Damage for each different type of dead Companion you have': [
    {
      scalable: true,
      formats: [],
    },
  ],
  'Plants have a 25% chance to immediately Overgrow when they enter your Presence for the first time':
    [
      {
        scalable: true,
        formats: [],
      },
    ],
  'Allies in your Presence share Charges with you': [],
  'If you would gain an Endurance Charge, Allies in your Presence gain that Charge instead': [],
  'If you would gain a Power Charge, Allies in your Presence gain that Charge instead': [],
  'If you would gain a Frenzy Charge, Allies in your Presence gain that Charge instead': [],
  'Companions in your Presence gain 1 Rage on hit': [
    {
      scalable: true,
      formats: [],
    },
  ],
  'Companions in your Presence have -20% to all Elemental Resistances': [
    {
      scalable: true,
      formats: [],
    },
  ],
  'Companions in your Presence Gain 20% of Damage as Extra Damage of a random Element': [
    {
      scalable: true,
      formats: [],
    },
  ],
  '40% reduced Presence Area of Effect': [
    {
      scalable: true,
      formats: ['negate'],
    },
  ],
  'Aura Skills have 25% increased Magnitudes': [
    {
      scalable: true,
      formats: [],
    },
  ],
  '30% reduced Mana Cost Efficiency of Command Skills': [
    {
      scalable: true,
      formats: ['negate'],
    },
  ],
  'Minions deal 60% increased Damage with Command Skills': [
    {
      scalable: true,
      formats: [],
    },
  ],
  'Minions have +20% to Chaos Resistance': [
    {
      scalable: true,
      formats: [],
    },
  ],
  'Companions have 12% increased Attack Speed': [
    {
      scalable: true,
      formats: [],
    },
  ],
  'Companions have 25% increased maximum Life': [
    {
      scalable: true,
      formats: [],
    },
  ],
}
