// 新版设置页与头部设置弹窗的公开文案；短词不用于其他页面。
export const settingsText = new Map([
  ['Import Settings', '导入设置'],
  ['Export Settings', '导出设置'],
  [
    'The following are your user settings. These are stored using local browser storage and will be',
    '以下是你的用户设置，保存在当前浏览器中。删除网站数据会导致这些设置',
  ],
  ['LOST', '丢失'],
  ['if site data is deleted.', '。'],
  ['Profiling', '性能分析'],
  [
    'Will show snackbars with profiling information when active.',
    '启用时显示包含性能分析信息的提示消息。',
  ],
  [
    'Shows reference text when hovering on keywords (Holding the SHIFT key will do the same when this option is inactive.)',
    '悬停在关键词上时显示说明文本（关闭此选项时，按住 SHIFT 键也可显示）。',
  ],
  ['Latest', '最新版本'],
  ["Allows for changing to a specific patch's data.", '可切换到指定版本的数据。'],
  ['Tooltip prices', '提示框价格'],
  [
    'Shows pricing data if available on currency object tooltips when active.',
    '启用后，通货提示框会显示可用的价格数据。',
  ],
  ['Specifies which currency should be used as the default currency.', '指定默认使用的计价通货。'],
  ['League', '赛区'],
  ['Challenge', '挑战赛区'],
  ['Challenge (HC)', '挑战赛区（专家）'],
  ['Standard', '永久赛区'],
  ['Standard (HC)', '永久赛区（专家）'],
  ['League to be used for pricing data.', '选择价格数据所属的赛区。'],
  ['Crafting settings', '制作设置'],
  ['Layout', '布局'],
  ['Classic', '经典'],
  ['Fullscreen', '全屏'],
  [
    'Toggles between classic and fullscreen mode for the crafting interface.',
    '切换制作界面的经典或全屏布局。',
  ],
  ['Compact mode', '紧凑模式'],
  ['Shows a more compact interface where possible.', '尽可能使用更紧凑的界面布局。'],
  ['Legacy elements', '旧版内容'],
  ['Show', '显示'],
  [
    'Shows legacy elements when active (can result in slower load times).',
    '启用时显示旧版内容（可能使加载变慢）。',
  ],
  ['Explicits output', '显式词缀显示'],
  ['Combined', '合并'],
  ['Split', '拆分'],
  [
    'Combined mode shows explicits (prefixes and suffixes) as two side-by-side columns.',
    '合并模式将显式词缀中的前缀与后缀显示为并排两列。',
  ],
  ['Filter effect', '筛选效果'],
  ['Cross out', '划除'],
  [
    'Specifies how tag filters should behave by either crossing out invalid elements or hiding them.',
    '选择划除或隐藏不符合标签筛选条件的内容。',
  ],
  ['Weight computations', '权重计算'],
  ['Will show weighting computation columns when active.', '启用时显示权重计算列。'],
  ['Item modifier output', '物品词缀显示'],
  ['Advanced', '高级'],
  [
    'Toggles between advanced (full modifier information) and classic (consolidated) mode for item output.',
    '切换物品的高级显示（完整词缀信息）或经典显示（合并信息）。',
  ],
  ['Items ordering', '物品排序'],
  ['Alphabetical', '字母顺序'],
  ['Drop level', '掉落等级'],
  [
    'Toggles between alphabetical or drop level as the ordering method for items.',
    '选择按字母顺序或掉落等级排列物品。',
  ],
  ['Tags filter', '标签筛选'],
  ['Active', '显示'],
  ['Hidden', '隐藏'],
  ['Will show tag filters when active.', '启用时显示标签筛选。'],
  ['Show item pseudos', '显示物品汇总属性'],
  [
    'Will show computed pseudos in item output (edps, pdps, total resists, etc).',
    '在物品信息中显示计算出的汇总属性（元素每秒伤害、物理每秒伤害、总抗性等）。',
  ],
  ['Bypass limits', '忽略词缀数量限制'],
  [
    'Allows the user to bypass item limitations in regards to maximum number of modifiers.',
    '允许忽略物品的最大词缀数量限制。',
  ],
  ['Show hidden stats', '显示隐藏属性'],
  ['Allows the user to view hidden modifier stats.', '允许查看词缀的隐藏属性。'],
  ['Show confidence', '显示累计成功率'],
  [
    'Toggles the confidence computation block in the calculations output.',
    '显示或隐藏计算结果中的累计成功率计算区。',
  ],
  ['Custom pricing', '自定义价格'],
])
