// 新版公开教程的人工译文；只用于 /simulator-usage 正文，不套用到用户步骤名。
export const simulatorHelpText = new Map<string, string>([
  ['How to use - Simulator', '流程模拟使用说明'],
  ['Creating a simulation', '创建模拟流程'],
  ['To create a simulation use the', '要创建模拟流程，点击'],
  ['New simulation', '新建模拟流程'],
  ['button. You will then be able to either', '按钮。随后可以选择'],
  ['Import an item', '导入装备'],
  ['using the games paste information,', '并粘贴游戏中的装备信息，或选择'],
  ['Use crafting setup', '使用当前制作配置'],
  [
    'which imports the current item in the crafting interface or',
    '来载入制作界面中的当前装备，也可以选择',
  ],
  ['Import a simulation', '导入一个流程'],
  ['where you can paste a previously exported simulation.', '并粘贴此前导出的流程数据。'],
  [
    'A simulation has multiple parameters which can be set in the header :',
    '流程顶部可以设置以下参数：',
  ],
  ['Generation type', '生成方式'],
  [':', '：'],
  ['Real-time', '实时'],
  [
    ': Runs the simulator in real-time where each action updates the simulator flow status as its ran.',
    '：每执行一个动作，就实时更新流程图中的运行状态。',
  ],
  ['Fixed', '固定次数'],
  [
    ': Allows the user to set a fixed limit number of either actions or succesful item generated.',
    '：指定动作次数或成功生成的物品数量上限。',
  ],
  ['Debug', '调试'],
  ['(upcoming feature)', '（尚未推出）'],
  [
    ': Will allow the user to continue operation between steps manually to better diagnose issues during simulation.',
    '：将允许手动逐步继续执行，以便诊断模拟中的问题。',
  ],
  ['Base cost', '基底成本'],
  [
    ': Allows the user to set up a base item cost to be factored into the pricing breakdowns.',
    '：设置基底物品的成本，将其计入费用明细。',
  ],
  ['Store Items', '保存结果装备'],
  [
    ": Let's the tool know how many successful items should be stored for review after the simulation is done.",
    '：指定模拟结束后保留多少件成功物品，供后续查看。',
  ],
  ['Distribution tables', '分布表'],
  [
    ': Will output additional breakdown tables relative to affix generation distributions.',
    '：额外输出词缀生成分布的明细表。',
  ],
  ['You can also', '也可以'],
  ['Save', '保存'],
  ['a simulation to local memory or', '流程到浏览器本地，或从本地'],
  ['Load', '载入'],
  ['a simulation from it.', '已保存的流程。'],
  [
    'Finally you can also create a simulation from a calculator state using the',
    '此外，在计算器提供',
  ],
  ['Create simulation', '创建模拟流程'],
  ['button when it is available.', '按钮时，可以根据当前计算器配置创建流程。'],
  ['Creating steps', '创建步骤'],
  ['To create a step you can click on the', '点击左侧面板的'],
  ['Add a step', '添加步骤'],
  [
    'button in the left pane. You can then drag it over to the simulator flow area by using the drag handler.',
    '按钮创建步骤，再通过拖动手柄将其拖入流程图区域。',
  ],
  [
    'The tool will automatically try to detect which step is the starting step by assuming that it is the step without any incoming routes. If it find multiples steps or none having this requirement it will fail when you try to run a simulation. You can manually specify which step is the starting step by using',
    '工具会尝试把没有传入路线的步骤识别为起始步骤。如果有多个步骤符合条件，或没有符合条件的步骤，启动模拟时会报错。也可以通过',
  ],
  ['Starting step', '起始步骤'],
  ['box.', '选择框手动指定。'],
  ['Editing a step', '编辑步骤'],
  [
    "You can edit a step by clicking either on its title bar or the crafting method output area. This toggles the step editing window where you can configure a step's parameters :",
    '点击步骤标题栏或制作方式显示区域，即可打开步骤编辑窗口，设置以下参数：',
  ],
  ['Action mode', '动作模式'],
  [': Either', '：可选择'],
  ['No action', '不执行操作'],
  ['or', '或'],
  ['Crafting Method', '制作方式'],
  ['.', '。'],
  ['On no valid route', '无有效后续路线时'],
  [
    ': This indicates which action to take when no succesful route is found. It can be set to either',
    '：指定没有满足条件的后续路线时如何处理。可以选择',
  ],
  ['Restart', '重新开始'],
  ["to go back to the simulation's start point,", '以返回流程起点，选择'],
  ['Loop', '循环'],
  ['where is will attempt the same action again or', '以再次执行同一动作，或选择'],
  ['End', '结束'],
  ['to consider the simulation a success.', '将本次模拟视为成功。'],
  ['Choose a crafting method', '选择制作方式'],
  [
    ': This is where you can select what crafting method should be used when running the step.',
    '：指定此步骤执行的制作方式。',
  ],
  ['Route priority order', '路线优先顺序'],
  [
    ": This is where you can order a step's route order priority to let the tool what should be evaluated first.",
    '：调整此步骤各条路线的判断顺序，确定先检查哪条路线。',
  ],
  ['Additionally you can', '此外，还可以'],
  ['remove', '移除'],
  ['copy', '复制'],
  ['a step as well as change its', '步骤，以及修改其'],
  ['title', '标题'],
  ['description', '说明'],
  ['. Once changes have been made you need to', '。修改完成后，必须点击'],
  ['Apply changes', '应用更改'],
  ['for them to be saved.', '才能保存。'],
  ['Linking steps', '连接步骤'],
  [
    'To link one step to another you need to click on the',
    '要连接两个步骤，先点击源步骤底栏中央的',
  ],
  ['linking icon', '连线图标'],
  [
    "in the center of the bottom bar of a step. You'll then be able to click the corresponding",
    '，再点击目标步骤上对应的',
  ],
  ['target icon', '目标图标'],
  ['on the desired step. This will create a', '，即可在两者之间创建一条'],
  ['route', '路线'],
  ['between both steps.', '。'],
  ['Links can be removed in the same fashion by clicking on the', '移除连线的方式类似：先点击'],
  ['and then the', '，再点击目标步骤上的'],
  ['destroy link icon', '断开连线图标'],
  ['on the desired step.', '。'],
  [
    'In addition to user defined routes between steps, a step can also have route conditions set up to go back to the start of the simulation or to the end (indicating a craft success) by using the',
    '除了步骤之间的自定义路线，还可以设置返回流程起点或结束流程（视为制作成功）的条件路线，分别使用步骤底栏中的',
  ],
  ['House', '房屋'],
  ['and', '与'],
  ['Flag', '旗帜'],
  ['icons respectively found in the bottom bar of a step in the simulator flow area.', '图标。'],
  ['Editing conditions', '编辑条件'],
  ["To edit a route's conditions you must click on the", '要编辑路线条件，点击连线路径中央的'],
  ['condition icon', '条件图标'],
  [
    "which is located in the center of the route's path. This toggles the link editing window where you can configure a route's parameters :",
    '，即可打开路线编辑窗口，设置以下参数：',
  ],
  ['Evaluation mode', '判断模式'],
  ['Passthrough', '直接通过'],
  [
    'where nothing should be checked and the route can always be taken or',
    '，不检查任何条件、始终允许经过该路线；或选择',
  ],
  ['Conditions', '条件判断'],
  [
    'where it will be evaluated for success against the requirement setup.',
    '，按配置的条件判断是否通过。',
  ],
  ['Conditions configuration', '条件配置（原站下文重复了无有效路线的处理说明，请以编辑器为准）'],
  ["to go back to the simulation's start point or", '以返回流程起点，或选择'],
  ['where is will attempt the same action again.', '以再次执行同一动作。'],
  ['the link or', '连线，或在此界面'],
  ['change its target', '更改目标'],
  ['from this interface. Once changes have been made you need to', '。修改完成后，必须点击'],
  ['Running a simulation', '运行模拟'],
  ['To start the simulation click on the', '点击'],
  ['Run simulation', '运行模拟'],
  [
    'button. While the simulation is running the left pane will be updated with the current simulation state including',
    '按钮开始执行。运行期间，左侧面板会更新当前状态，包括',
  ],
  ['run count', '运行次数'],
  [',', '、'],
  ['steps ran', '已执行步骤数'],
  ['items completed', '已完成物品数'],
  ['and more.', '等。'],
  [
    "The simulator flow area will also be updated with each step's and route's current state with",
    '流程图也会更新各步骤与路线的状态，显示',
  ],
  ['success', '成功'],
  ['failure', '失败'],
  [
    'counts and the number of times each step or route has been run or passed through.',
    '次数，以及每个步骤的执行次数、每条路线的通过次数。',
  ],
  ['A step action is considered a', '只要经过此步骤的任一后续路线，就将该步骤动作视为'],
  ['if any of its outgoing route is used including the', '，包括'],
  ['restart', '重新开始'],
  ['end', '结束'],
  ['routes.', '路线。'],
  [
    'After the simulation has completed the tool will present the user with a linear breakdown of all step statistics as well as crafting costs averages.',
    '模拟完成后，会按步骤顺序显示统计明细及平均制作成本。',
  ],
])
